# Generated by Django 5.1.1 on 2024-09-18 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='food_title',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='image',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='desciption',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='food_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='foodimages'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.category'),
        ),
    ]
