# Generated by Django 5.1.1 on 2024-09-29 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_remove_fooditem_category_remove_fooditem_desciption_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='category_name',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fooditems', to='menu.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='description',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='food_title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='image',
            field=models.ImageField(null=True, upload_to='foodimages'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
